apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  NODE_ENV: "development"
  FRONTEND_URL: "http://localhost:30001"
  CLOUDINARY_CLOUD_NAME: "*******"
  SENDGRID_EMAIL: "**********"