apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  JWT_SECRET: "*********"
  MONGO_URI: "mongodb://chat-mongo:27017/chatapp"
  CLOUDINARY_API_KEY: "***********"
  CLOUDINARY_API_SECRET: "**********"
  SENDGRID_API_KEY: "*****************************************"