apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-backend-config
data:
  PORT: "5000"
  FRONTEND_URL: "http://chat-frontend"
  CLOUDINARY_CLOUD_NAME: "xxxxxxxxxx"
  SENDGRID_EMAIL: "xxxxxxxxxxxxxx"
